language: rust

rust:
  - stable

cache: cargo

install:
  - rustup component add rustfmt

script:
  - cargo build --features=ci
  - cargo test --features=ci -- --test-threads=1
  - cargo fmt -- --check
